version: '3.8'

services:
    trip-database:
        image: postgres:17.2-bookworm
        container_name: trip-database
        restart: on-failure
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: trip
        ports:
            - '5436:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
